package nuevojarvisualizador.gui;
import java.awt.HeadlessException;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.zip.ZipEntry;
import java.util.zip.ZipInputStream;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
/**
 *
 * @author Javier
 */
public class MiNuevoMainFrame extends javax.swing.JFrame {
    /**
     * Creates new form MiNuevoMainFrame
     */
    public MiNuevoMainFrame() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Etiqueta = new javax.swing.JLabel();
        Visualizador = new javax.swing.JButton();
        StatusPanel = new javax.swing.JPanel();
        status = new javax.swing.JLabel();
        Búsqueda = new javax.swing.JTextField();
        PanelEntrada = new javax.swing.JScrollPane();
        Entradas = new javax.swing.JList<>();
        MenuBar = new javax.swing.JToolBar();
        ToolBar = new javax.swing.JButton (new 
            javax.swing.ImageIcon (new javax.swing.ImageIcon(getClass()
                .getResource("/nuevojarvisualizador/gui/zip.png")).getImage()
            .getScaledInstance(16,16,java.awt.Image.SCALE_SMOOTH)));
    Menú = new javax.swing.JMenuBar();
    AplicacionMenu = new javax.swing.JMenu();
    SalidaMenu = new javax.swing.JMenuItem();
    AyudaMenu = new javax.swing.JMenu();
    DetallesMenu = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("JarVisiolab");
    setIconImage(new javax.swing.ImageIcon(getClass().getResource("/nuevojarvisualizador/gui/zip.png")).getImage());

    Etiqueta.setText("Archivo");

    Visualizador.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
    Visualizador.setText("Ver contenido");
    Visualizador.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            VisualizadorActionPerformed(evt);
        }
    });

    StatusPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Volcado"));

    status.setText("panel");

    javax.swing.GroupLayout StatusPanelLayout = new javax.swing.GroupLayout(StatusPanel);
    StatusPanel.setLayout(StatusPanelLayout);
    StatusPanelLayout.setHorizontalGroup(
        StatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(StatusPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    StatusPanelLayout.setVerticalGroup(
        StatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    Búsqueda.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            BúsquedaActionPerformed(evt);
        }
    });

    Entradas.setModel(new javax.swing.AbstractListModel<String>() {
        String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
        public int getSize() { return strings.length; }
        public String getElementAt(int i) { return strings[i]; }
    });
    PanelEntrada.setViewportView(Entradas);

    MenuBar.setRollover(true);

    ToolBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nuevojarvisualizador/gui/screen.png"))); // NOI18N
    ToolBar.setFocusable(false);
    ToolBar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    ToolBar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    ToolBar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            ToolBarActionPerformed(evt);
        }
    });
    MenuBar.add(ToolBar);

    AplicacionMenu.setText("Aplicación");

    SalidaMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
    SalidaMenu.setText("Salir");
    SalidaMenu.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            SalidaMenuActionPerformed(evt);
        }
    });
    AplicacionMenu.add(SalidaMenu);

    Menú.add(AplicacionMenu);

    AyudaMenu.setText("Ayuda");

    DetallesMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
    DetallesMenu.setText("Detalles");
    DetallesMenu.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            DetallesMenuActionPerformed(evt);
        }
    });
    AyudaMenu.add(DetallesMenu);

    Menú.add(AyudaMenu);

    setJMenuBar(Menú);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(StatusPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PanelEntrada)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(Etiqueta, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(Búsqueda, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(Visualizador)))
            .addContainerGap())
        .addGroup(layout.createSequentialGroup()
            .addComponent(MenuBar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(MenuBar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(19, 19, 19)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(Etiqueta, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(Visualizador)
                .addComponent(Búsqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(PanelEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(StatusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VisualizadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisualizadorActionPerformed
        AnalizarJarFile();
    }//GEN-LAST:event_VisualizadorActionPerformed

    private void BúsquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BúsquedaActionPerformed
        AnalizarJarFile();
    }//GEN-LAST:event_BúsquedaActionPerformed

    private void AnalizarJarFile() throws HeadlessException {
        status.setText("Analizando ficheros JAR");
        try {
            DefaultListModel model = new DefaultListModel();
            ZipInputStream zip = new ZipInputStream(new FileInputStream(Búsqueda.getText()));
            for (ZipEntry entry = zip.getNextEntry(); entry != null; entry = zip.getNextEntry()){
                model.addElement(entry.getName());
            }
            Entradas.setModel(model);
            status.setText("-Ficheros detectados 'L',:"+ model.size());
        } catch(IOException ioe) {
            status.setText("- Archivos encontrados: 0");
            JOptionPane.showMessageDialog(this, ioe.getLocalizedMessage(), "'L'. Ups! - Error a la vista",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void SalidaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalidaMenuActionPerformed
        System.exit(1);
    }//GEN-LAST:event_SalidaMenuActionPerformed

    private void DetallesMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DetallesMenuActionPerformed
        NuevoDialogo dialog = new NuevoDialogo (this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_DetallesMenuActionPerformed

    private void ToolBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToolBarActionPerformed
        AnalizarJarFile();
    }//GEN-LAST:event_ToolBarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MiNuevoMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MiNuevoMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MiNuevoMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MiNuevoMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MiNuevoMainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AplicacionMenu;
    private javax.swing.JMenu AyudaMenu;
    private javax.swing.JTextField Búsqueda;
    private javax.swing.JMenuItem DetallesMenu;
    private javax.swing.JList<String> Entradas;
    private javax.swing.JLabel Etiqueta;
    private javax.swing.JToolBar MenuBar;
    private javax.swing.JMenuBar Menú;
    private javax.swing.JScrollPane PanelEntrada;
    private javax.swing.JMenuItem SalidaMenu;
    private javax.swing.JPanel StatusPanel;
    private javax.swing.JButton ToolBar;
    private javax.swing.JButton Visualizador;
    private javax.swing.JLabel status;
    // End of variables declaration//GEN-END:variables
}
